### PR TITLE
feat(player): add slide gesture to song tile for playing next song

### PR DESCRIPTION
**Pull request by DarkNinja15**
<p align="center">
  Image 1
  Image 2
</p>

On sliding right on any song or video tile the user will get an option to play the selected song next.

### CODE REVIEW

**Comment by DarkNinja15** [comment]
@anandnet Hi there!, please review this PR

**Comment by DarkNinja15** [comment]
Hey @anandnet I think there is some problem with the workflows.
After the last failure of the build I updated the project to use java 17 and kotlin 1.8.0,
I tweaked the code_quality.yml file and made a new one code_quality_test.yml.
You can review it I have just installed java 17 on the runner before running "flutter build apk" command.

I have also tested the app on linux and android and it is working fine.
Please review it and give me some feedback on whether we can update the existing workflows or not.

**Comment by anandnet** [comment]
Yes, there is some issue with the workflow which i had to check. Thanks for looking into it. Could you please raise a separate PR for that?

**Comment by DarkNinja15** [comment]
Sure

**Comment by anandnet** [comment]
For now just reset 4 top commits `git reset HEAD~4` and force push `git push -f` . I'll merge this PR.

**Comment by DarkNinja15** [comment]
ok, by the way I have already raised a pr for workflows.

**Comment by DarkNinja15** [comment]
you can merge this too now.

**Pull request merged**
